services:
  - type: web
    name: aapryl-efficacy
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: /health
        destination: /health/index.html
      - type: rewrite
        source: /*
        destination: /index.html
